// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int N = Integer.parseInt(args[0]);
	   int result1 = 0;
	   int result2 =0;
	   for (int i = 0; i <N; i++) {
	   double random = Math.random();
	   if (random > 0.5) {
		result1++; 
	   } else {
		result2++;
	   }
	   } 
	   double ratio = (double) result1 / result2;
	   System.out.println("> 0.5: " +result1 + " times");
	   System.out.println("<= 0.5: " +result2 + " times");
	   if (ratio != 0) {
		System.out.println("Ratio: " + ratio);
	   }
	}
}
